validate

diff --git a/.github/workflows/validate.yml b/.github/workflows/validate.yml
--- a/.github/workflows/validate.yml
+++ b/.github/workflows/validate.yml
@@ -71,6 +71,14 @@ jobs:
             fi
           done
 
+          if [ $ERROR_FLAG -eq 1 ]; then
+            echo -e "Errores encontrados durante la validación:\n$ERROR_MESSAGES"
+            curl -X POST -H "Authorization: token ${{ secrets.TOKEN_GITHUB }}" \
+              -d "{\"body\": \"Errores encontrados en la validación del PR:\n$ERROR_MESSAGES\"}" \
+              "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
+            exit 1
+          fi
+
       # Close the PR if there are validation errors
       - name: Cerrar PR si hay errores
         if: failure()
