python

diff --git a/.github/workflows/validate.yml b/.github/workflows/validate.yml
--- a/.github/workflows/validate.yml
+++ b/.github/workflows/validate.yml
@@ -42,21 +42,24 @@ jobs:
             python "scripts/validate_exercise_$exercise.py" ./ ${{ env.language }} >> exercise_errors.txt || true
           done
 
-      - name: Procesar errores
-        id: process_errors
-        run: |
-          # Combinar errores
-          cat general_errors.txt exercise_errors.txt > all_errors.txt || true
+          - name: Procesar errores
+          id: process_errors
+          run: |
+            # Combinar errores
+            cat general_errors.txt exercise_errors.txt > all_errors.txt || true
 
-          # Agregar comentario al PR si hay errores
-          if [ -s all_errors.txt ]; then
-            echo "Se encontraron errores en la validación. Publicando comentario..." 
-            gh pr comment ${{ github.event.pull_request.number }} --body "$(cat all_errors.txt)" --repo ${{ github.repository }}
-            echo "validation_status=failure" >> $GITHUB_ENV
-          else
-            echo "¡Validación exitosa!" 
-            echo "validation_status=success" >> $GITHUB_ENV
-          fi
+            # Agregar comentario al PR si hay errores
+            if [ -s all_errors.txt ]; then
+              echo "Se encontraron errores en la validación. Publicando comentario..." 
+              gh pr comment 68 --body "$(cat all_errors.txt)" --repo Akradeveloper/Selenium-exercises
+              echo "validation_status=failure" >> $GITHUB_ENV
+            else
+              echo "¡Validación exitosa!" 
+              echo "validation_status=success" >> $GITHUB_ENV
+            fi
+          shell: /usr/bin/bash -e {0}
+          env:
+            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Agregar el token aquí
 
       - name: Establecer estado del PR
         if: ${{ env.validation_status == 'failure' }}
