Update validate.yml

diff --git a/.github/workflows/validate.yml b/.github/workflows/validate.yml
--- a/.github/workflows/validate.yml
+++ b/.github/workflows/validate.yml
@@ -22,16 +22,14 @@ jobs:
 
       # Encontrar las subcarpetas de ejercicios
       - name: Encontrar subcarpetas de ejercicios
-        id: find_exercises
         run: |
-   
-      # Buscar las subcarpetas de ejercicios que contienen package.json o pom.xml
-          EXERCISE_FOLDERS=$(find ./* -maxdepth 1 -type d \
-      \( -exec test -e "{}/package.json" \; -o -exec test -e "{}/pom.xml" \; \) \
-      -exec basename {} \;)
-
-    echo "Subcarpetas encontradas: $EXERCISE_FOLDERS"
-    echo "::set-output name=folders::$EXERCISE_FOLDERS"
+           if [ ! -d "./Selenium-exercises" ]; then
+              echo "ERROR: No se encuentra la carpeta Selenium-exercises"
+              exit 1
+           fi
+           EXERCISE_FOLDERS=$(find ./Selenium-exercises/* -maxdepth 1 -type d \( -exec test -e "{}/package.json" \; -o -exec test -e "{}/pom.xml" \; \) -exec basename {} \;)
+              echo "Subcarpetas encontradas: $EXERCISE_FOLDERS"
+              echo "::set-output name=folders::$EXERCISE_FOLDERS"
 
       # Paso 3: Validar cada subcarpeta de ejercicios
       - name: Validar cada ejercicio
